# 23hydropathy.py by Christina Chen

import sys

def kdhydro(x):
	if x == 'a': print('1.80')
	if x == 'b': print('Not an amino acid.')
	if x == 'c': print('2.50')
	if x == 'd': print('-3.50')
	if x == 'e': print('-3.50')
	if x == 'f': print('2.80')
	if x == 'g': print('-0.40')
	if x == 'h': print('-3.20')
	if x == 'i': print('4.50')
	if x == 'j': print('Not an amino acid.')
	if x == 'k': print('-3.90')
	if x == 'l': print('3.80')
	if x == 'm': print('1.90')
	if x == 'n': print('-3.50')
	if x == 'o': print('Not an amino acid.')
	if x == 'p': print('-1.60')
	if x == 'q': print('-3.50')
	if x == 'r': print('-4.50')
	if x == 's': print('-0.80')
	if x == 't': print('-0.70')
	if x == 'u': print('Not an amino acid.')
	if x == 'v': print('4.20')
	if x == 'w': print('-.90')
	if x == 'x': print('Not an amino acid.')
	if x == 'y': print('-1.30')
	if x == 'z': print('Not an amino acid.')
	
kdhydro('a')
kdhydro('c')
kdhydro('r')
kdhydro('z')